
[package]
name = "quizgame-frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-embed = "0.1.0"
actix-files = "0.6.2"
actix-rt = "2.8.0"
actix-web = "4.3.1"
rust-embed = "6.6.1"
